import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "@/theme";
import AppLayout from "./AppLayout";

export const metadata = {
  title: "UCP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <AppLayout>{children}</AppLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
